import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Song = { id:string; title:string; artist:string; key:string; bpm:number; type:string; source:string; url:string; chords:string[]; difficulty:'Easy'|'Medium'|'Advanced'; publicDomain?:boolean };
const songs:Song[] = [
 {id:'amazing-grace',title:'Amazing Grace',artist:'Traditional',key:'G',bpm:78,type:'Lead sheet',source:'Public domain',url:'https://www.loc.gov/',chords:['G','C','D','Em'],difficulty:'Easy',publicDomain:true},
 {id:'house-rising-sun',title:'House of the Rising Sun',artist:'Traditional',key:'Am',bpm:92,type:'Chords',source:'MusicBrainz metadata',url:'https://musicbrainz.org/',chords:['Am','C','D','F','E'],difficulty:'Medium'},
 {id:'wayfaring',title:'Wayfaring Stranger',artist:'Traditional',key:'Em',bpm:72,type:'Lead sheet',source:'Public domain',url:'https://www.loc.gov/',chords:['Em','G','B7','Am'],difficulty:'Easy',publicDomain:true},
 {id:'scarborough',title:'Scarborough Fair',artist:'Traditional',key:'Am',bpm:82,type:'Guitar',source:'Public domain',url:'https://www.loc.gov/',chords:['Am','G','F','E'],difficulty:'Easy',publicDomain:true},
 {id:'greensleeves',title:'Greensleeves',artist:'Traditional',key:'Am',bpm:88,type:'Lead sheet',source:'Public domain',url:'https://www.loc.gov/',chords:['Am','G','F','E'],difficulty:'Easy',publicDomain:true},
 {id:'blues',title:'12-Bar Blues in A',artist:'FreeScore Original',key:'A',bpm:96,type:'Practice',source:'FreeScore',url:'#',chords:['A7','D7','E7'],difficulty:'Easy',publicDomain:true}
];
const keys=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const shapes:Record<string,string[]>={C:['x','3','2','0','1','0'],G:['3','2','0','0','0','3'],D:['x','x','0','2','3','2'],A:['x','0','2','2','2','0'],E:['0','2','2','1','0','0'],Am:['x','0','2','2','1','0'],Em:['0','2','2','0','0','0'],F:['1','3','3','2','1','1'],B7:['x','2','1','2','0','2'],A7:['x','0','2','0','2','0'],D7:['x','x','0','2','1','2'],E7:['0','2','0','1','0','0'],B:['x','2','4','4','4','2'],Bb:['x','1','3','3','3','1']};
function transposeChord(chord:string, steps:number){const minor=chord.endsWith('m'); const base=minor?chord.slice(0,-1):chord; const i=keys.indexOf(base); if(i<0)return chord; return keys[(i+steps+12)%12]+(minor?'m':'');}
function App(){
 const [query,setQuery]=useState(''); const [tab,setTab]=useState('home'); const [selected,setSelected]=useState<Song|null>(null); const [favorites,setFavorites]=useState<string[]>(()=>JSON.parse(localStorage.getItem('fs-favorites')||'[]')); const [setlist,setSetlist]=useState<string[]>(()=>JSON.parse(localStorage.getItem('fs-setlist')||'[]')); const [shift,setShift]=useState(0); const [bpm,setBpm]=useState(90); const [playing,setPlaying]=useState(false); const [metronome,setMetronome]=useState(false); const [easy,setEasy]=useState(true); const [dark,setDark]=useState(()=>localStorage.getItem('fs-theme')==='dark');
 useEffect(()=>{localStorage.setItem('fs-favorites',JSON.stringify(favorites))},[favorites]); useEffect(()=>{localStorage.setItem('fs-setlist',JSON.stringify(setlist))},[setlist]); useEffect(()=>{localStorage.setItem('fs-theme',dark?'dark':'light');document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 const results=useMemo(()=>songs.filter(s=>(`${s.title} ${s.artist} ${s.type}`.toLowerCase()).includes(query.toLowerCase()) && (tab==='favorites'?favorites.includes(s.id):tab==='setlist'?setlist.includes(s.id):true)),[query,tab,favorites,setlist]);
 const open=(s:Song)=>{setSelected(s);setBpm(s.bpm);setShift(0)};
 const toggleFav=(id:string)=>setFavorites(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]); const toggleSet=(id:string)=>setSetlist(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]);
 if(selected)return <div className="app"><header><button className="icon" onClick={()=>setSelected(null)}>←</button><b>FreeScore</b><button className="icon" onClick={()=>toggleFav(selected.id)}>{favorites.includes(selected.id)?'♥':'♡'}</button></header><main className="reader"><div className="readerTop"><div><span className="eyebrow">{selected.type}</span><h1>{selected.title}</h1><p>{selected.artist} · Original key {selected.key}</p></div><button className="primary" onClick={()=>toggleSet(selected.id)}>{setlist.includes(selected.id)?'✓ In Setlist':'+ Setlist'}</button></div><div className="controls"><button onClick={()=>setShift(s=>s-1)}>− Key</button><strong>Key: {transposeChord(selected.key,shift)}</strong><button onClick={()=>setShift(s=>s+1)}>+ Key</button><label>BPM <input type="range" min="40" max="220" value={bpm} onChange={e=>setBpm(+e.target.value)}/><b>{bpm}</b></label><button className={playing?'primary':''} onClick={()=>setPlaying(!playing)}>{playing?'■ Stop':'▶ Play'}</button></div><section className="score"><div className="music-placeholder">♪ ♫ ♪ ♩ ♫ ♪</div><h2>{easy?'Easy / Beginner Arrangement':'Standard Arrangement'}</h2><p className="muted">FreeScore displays metadata and links to lawful sheet-music sources. Copyrighted sheet music is not copied into this app.</p><div className="chordRow">{selected.chords.map((c,i)=><div className="chordCard" key={i}><b>{transposeChord(c,shift)}</b><div className="fret">{(shapes[c]||['x','x','x','x','x','x']).map((v,j)=><span key={j}>{v}</span>)}</div></div>)}</div><div className="lyrics"><p><b>Practice progression</b></p><p>{selected.chords.map((c,i)=><span key={i}>{transposeChord(c,shift)} &nbsp; </span>)}</p><p className="muted">Strum: ↓ ↓↑ ↑↓↑ · Count 1 & 2 & 3 & 4 &</p></div></section><div className="source"><b>Source</b><span>{selected.source}</span><a href={selected.url} target="_blank" rel="noreferrer">Open legal source ↗</a></div></main><footer><button onClick={()=>setMetronome(!metronome)}>◉ Metronome {metronome?'ON':'OFF'}</button><button onClick={()=>setEasy(!easy)}>✨ {easy?'Easy mode':'Standard'}</button></footer></div>;
 return <div className="app"><header><div className="brand"><span className="logo">♪</span><div><b>FreeScore</b><small>Play. Practice. Perform.</small></div></div><button className="icon" onClick={()=>setDark(!dark)}>{dark?'☀':'☾'}</button></header><main><section className="hero"><span className="pill">FREE + LEGAL MUSIC TOOLS</span><h1>Your music stand,<br/><em>everywhere.</em></h1><p>Find music, transpose keys, learn chords, build setlists, and practice anywhere.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search songs, artists, chords..."/><kbd>⌘ K</kbd></div></section><nav className="tabs">{[['home','Discover'],['favorites','♥ Favorites'],['setlist','☷ Setlist']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav><section className="grid">{results.map(s=><article className="song" key={s.id} onClick={()=>open(s)}><div className="songIcon">{s.type==='Guitar'?'🎸':s.type==='Lead sheet'?'🎼':'♫'}</div><div className="songInfo"><div className="eyebrow">{s.type} · {s.difficulty}</div><h3>{s.title}</h3><p>{s.artist}</p><div className="chips"><span>Key {s.key}</span><span>{s.bpm} BPM</span>{s.publicDomain&&<span>Public domain</span>}</div></div><button className="heart" onClick={e=>{e.stopPropagation();toggleFav(s.id)}}>{favorites.includes(s.id)?'♥':'♡'}</button></article>)}{results.length===0&&<div className="empty"><h2>No songs found</h2><p>Try another title or artist.</p></div>}</section><section className="tools"><h2>Practice tools</h2><div className="toolGrid"><button onClick={()=>setMetronome(!metronome)}><b>◉</b><span>Metronome</span><small>{metronome?'Running':'Tap to start'}</small></button><button onClick={()=>setEasy(!easy)}><b>✨</b><span>Easy Mode</span><small>{easy?'Beginner friendly':'Standard'}</small></button><button onClick={()=>setTab('setlist')}><b>☷</b><span>Setlists</span><small>{setlist.length} songs</small></button><button onClick={()=>setTab('favorites')}><b>♥</b><span>Favorites</span><small>{favorites.length} songs</small></button></div></section><section className="legal"><b>About FreeScore</b><p>FreeScore is designed to help musicians discover and practice music without redistributing copyrighted sheet music. Search results can link to authorized or public-domain sources. Music metadata can be powered by MusicBrainz, whose API provides artist, recording, release and work metadata. </p></section></main><footer><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>⌂<span>Home</span></button><button onClick={()=>document.querySelector<HTMLInputElement>('.search input')?.focus()}>⌕<span>Search</span></button><button onClick={()=>setTab('favorites')}>♥<span>Library</span></button><button onClick={()=>setDark(!dark)}>{dark?'☀':'☾'}<span>Theme</span></button></footer></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
