const NOTE_INDEX:Record<string,number>={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11};
const NOTE_NAMES=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'];
const ROOTS:Record<string,number[]>={C:[0,4,7],Cm:[0,3,7],D:[2,6,9],Dm:[2,5,9],E:[4,8,11],Em:[4,7,11],F:[5,9,0],Fm:[5,8,0],G:[7,11,2],Gm:[7,10,2],A:[9,1,4],Am:[9,0,4],B:[11,3,6],Bm:[11,2,6],C7:[0,4,7,10],D7:[2,6,9,0],E7:[4,8,11,2],F7:[5,9,0,3],G7:[7,11,2,5],A7:[9,1,4,7],B7:[11,3,6,9]};
function normalizeChord(ch:string){return ch.replace(/[^A-G#b0-9m]/g,'')}
function notesFor(ch:string){const clean=normalizeChord(ch);if(ROOTS[clean])return ROOTS[clean];const root=clean.match(/^[A-G](?:#|b)?/)?.[0]||'C';const n=NOTE_INDEX[root]??0;return clean.includes('m')?[n,(n+3)%12,(n+7)%12]:[n,(n+4)%12,(n+7)%12]}
function piano(ch:string){const notes=notesFor(ch);const white=['C','D','E','F','G','A','B'];return `<div class="pianoWrap"><div class="pianoLabel">Piano voicing · ${ch}</div><div class="pianoKeys">${white.map((w,i)=>{const octave=4+Math.floor(i/7);const note=`${w}${octave}`;const active=notes.some(n=>NOTE_NAMES[n]===w);return `<div class="pianoKey ${active?'active':''}"><span>${active?note:''}</span></div>`}).join('')}</div><div class="pianoNotes">${notes.map(n=>NOTE_NAMES[n]).join(' · ')}</div></div>`}
function staff(chords:string[]){const safe=chords.slice(0,8);return `<div class="scoreView"><div class="scoreTitle">Chord Score · accompaniment</div><svg viewBox="0 0 760 170" role="img" aria-label="Chord accompaniment score">${[48,68,88,108,128].map(y=>`<line x1="30" y1="${y}" x2="730" y2="${y}" />`).join('')}<text x="38" y="83" class="clef">𝄞</text>${safe.map((c,i)=>{const x=115+i*78;const n=notesFor(c)[0];const y=128-(n%12)*4;return `<g><text x="${x-10}" y="35" class="scoreChord">${c}</text><ellipse cx="${x}" cy="${Math.max(52,Math.min(124,y))}" rx="10" ry="7" class="note"/><line x1="${x+9}" y1="${Math.max(52,Math.min(124,y))}" x2="${x+9}" y2="${Math.max(25,Math.min(110,y-48))}" class="stem"/></g>`}).join('')}</svg><small>This is an accompaniment score derived from the chord progression, not an official melody transcription.</small></div>`}
function enhance(){document.querySelectorAll<HTMLElement>('.songSheet').forEach(sheet=>{if(sheet.dataset.enhanced==='1')return;const workspace=sheet.querySelector<HTMLElement>('.workspace');if(!workspace)return;const chordNodes=[...workspace.querySelectorAll<HTMLElement>('.generatedChords span')];const chords=chordNodes.map(n=>n.textContent||'').filter(Boolean);if(!chords.length)return;sheet.dataset.enhanced='1';const controls=document.createElement('div');controls.className='notationControls';controls.innerHTML='<button type="button" data-view="chords">🎸 Chords</button><button type="button" data-view="piano">🎹 Piano</button><button type="button" data-view="score">🎼 Score</button>';workspace.parentElement?.insertBefore(controls,workspace);const panel=document.createElement('div');panel.className='notationPanel';workspace.parentElement?.insertBefore(panel,workspace);const render=(view:string)=>{if(view==='piano'){panel.innerHTML=`<div class="pianoGrid">${chords.map(piano).join('')}</div>`}else if(view==='score'){panel.innerHTML=staff(chords)}else{panel.innerHTML=''}};controls.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{controls.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view||'chords')}));});}
new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});
setTimeout(enhance,100);
